CREATE DATABASE JOLLYBEEWEB
GO
USE JOLLYBEEWEB
GO
CREATE TABLE NGUOIDUNG
( USERNAME NVARCHAR(20) PRIMARY KEY,
  PASSWORD NVARCHAR(128),
  IDENTIFY BIT default 1)
GO
CREATE TABLE KHACHHANG
( IDKH INT IDENTITY(1,1) PRIMARY KEY,
  USERNAME NVARCHAR(20) FOREIGN KEY REFERENCES NGUOIDUNG(USERNAME), -- FOREIGN KEY CONSTRAINT
  HOTEN NVARCHAR(50),
  EMAIL NVARCHAR(50),
  SDT NVARCHAR(50),
  DIACHI NVARCHAR(50),
  UNIQUE(USERNAME))
  GO
  CREATE TABLE VOUCHER
(IDCoupon INT IDENTITY(1,1) PRIMARY KEY,
 TENVOUCHER NVARCHAR(50),
 GIATRI FLOAT,
 HSD DATETIME,
 StateCoupon bit default 1
)
  GO
  CREATE TABLE QLVOUCHER
(IDCoupon INT FOREIGN KEY REFERENCES VOUCHER(IDCoupon),
 IDKH INT FOREIGN KEY REFERENCES KHACHHANG(IDKH),
 StateUse bit,
 PRIMARY KEY (IDCoupon,IDKH)
 )
 ALTER TABLE QLVOUCHER ADD NGAYTHEM DATETIME
 ALTER TABLE QLVOUCHER ADD NGAYSD DATETIME
  GO
 CREATE TABLE LOAISP
	 ( IDLSP INT IDENTITY(1,1) PRIMARY KEY,
	  TENLOAISP NVARCHAR(50))
	  GO
CREATE TABLE SANPHAM
(IDSP INT IDENTITY(1,1) PRIMARY KEY,
 IDLSP INT FOREIGN KEY REFERENCES LOAISP(IDLSP), -- FOREIGN KEY CONSTRAINT
 HINHANH NVARCHAR(200),
 TENSP NVARCHAR(50),
 MOTA NVARCHAR(100),
 DONGIA FLOAT,
 StateProduct BIT default 1)
	  GO
CREATE TABLE HINHANHSP
(IDHA INT IDENTITY(1,1) PRIMARY KEY,
 IDSP INT FOREIGN KEY REFERENCES SANPHAM(IDSP),
 IMAGE NVARCHAR(200),
)
	  GO
CREATE TABLE PAYMENTMETHOD
(IDPAYMENT INT IDENTITY(1,1) PRIMARY KEY,
 METHODNAME NVARCHAR(50)
)
	  GO
CREATE TABLE DONHANG
( IDDH INT IDENTITY(1,1) PRIMARY KEY,
  IDKH INT FOREIGN KEY REFERENCES KHACHHANG(IDKH), -- FOREIGN KEY CONSTRAINT
  NGAYDAT DATE,
  IDPAYMENT INT FOREIGN KEY REFERENCES PAYMENTMETHOD(IDPAYMENT), -- FOREIGN KEY CONSTRAINT
  TONGTIEN FLOAT,
  PHISHIP FLOAT,
  KHUYENMAI FLOAT,
  THANHTIEN FLOAT,
  LastestState NVARCHAR(50))
  ALTER TABLE DONHANG ADD HOANTAT BIT default 0 
  ALTER TABLE DONHANG ADD HUY BIT default 0
  ALTER TABLE DONHANG ADD DeleteOrder BIT default 0
  ALTER TABLE DONHANG ADD IDCoupon INT FOREIGN KEY REFERENCES VOUCHER(IDCoupon)
GO 
CREATE TABLE CHITIETDONHANG
(IDDH INT FOREIGN KEY REFERENCES DONHANG(IDDH), -- FOREIGN KEY CONSTRAINT
 IDSP INT FOREIGN KEY REFERENCES SANPHAM(IDSP), -- FOREIGN KEY CONSTRAINT
 SOLUONG INT,
 GIATIEN FLOAT,
 PRIMARY KEY (IDDH,IDSP))
GO
CREATE TABLE TRANGTHAIDH
(IDSTATE INT IDENTITY(1,1) PRIMARY KEY,
 IDDH INT FOREIGN KEY REFERENCES DONHANG(IDDH),
 CurrentState NVARCHAR(50),
 StateTime Datetime
)

Select * from VOUCHER join QLVOUCHER on VOUCHER.IDCoupon=QLVOUCHER.IDCoupon
and IDKH=1

Select * from VOUCHER join QLVOUCHER on VOUCHER.IDCoupon=QLVOUCHER.IDCoupon
and IDKH=1 where VOUCHER.IDCoupon  not in (select DONHANG.IDCoupon from DONHANG where IDKH=1  AND IDCoupon IS NOT NULL)

SELECT *
FROM VOUCHER
JOIN QLVOUCHER ON VOUCHER.IDCoupon = QLVOUCHER.IDCoupon
WHERE VOUCHER.IDCoupon NOT IN (
    SELECT IDCoupon
    FROM DONHANG
    WHERE IDKH = 1
	AND IDCoupon IS NOT NULL
)
OR VOUCHER.IDCoupon IS NULL;


