//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWEBJollybee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANG = new HashSet<CHITIETDONHANG>();
            this.TRANGTHAIDH = new HashSet<TRANGTHAIDH>();
        }
    
        public int IDDH { get; set; }
        public Nullable<int> IDKH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> IDPAYMENT { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public Nullable<double> PHISHIP { get; set; }
        public Nullable<double> KHUYENMAI { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public string LastestState { get; set; }
        public Nullable<bool> HOANTAT { get; set; }
        public Nullable<bool> HUY { get; set; }
        public Nullable<bool> DeleteOrder { get; set; }
        public Nullable<int> IDCoupon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PAYMENTMETHOD PAYMENTMETHOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHAIDH> TRANGTHAIDH { get; set; }
    }
}
