//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWEBJollybee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANHSP
    {
        public int IDHA { get; set; }
        public Nullable<int> IDSP { get; set; }
        public string IMAGE { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
