//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWEBJollybee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLVOUCHER
    {
        public int IDCoupon { get; set; }
        public int IDKH { get; set; }
        public Nullable<bool> StateUse { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
        public Nullable<System.DateTime> NGAYSD { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
