//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWEBJollybee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANG = new HashSet<CHITIETDONHANG>();
            this.HINHANHSP = new HashSet<HINHANHSP>();
        }
    
        public int IDSP { get; set; }
        public Nullable<int> IDLSP { get; set; }
        public string HINHANH { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<bool> StateProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANHSP> HINHANHSP { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
